application: yunlei-resume
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|jpeg))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|jpeg))

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: static/\1
  upload: static/(.*\.webp)
  
#make sure the font works  
- url: /fonts
  static_dir: fonts
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /(.*\.woff)
  static_files: static/\1
  upload: static/(.*\.woff)
  mime_type: application/font-woff

- url: /(.*\.svg)
  static_files: static/\1
  upload: static/(.*\.svg)
  mime_type: image/svg+xml

- url: /(.*\.eot)
  static_files: static/\1
  upload: static/(.*\.eot)
  mime_type: application/vnd.ms-fontobject

- url: /(.*\.ttf)
  static_files: static/\1
  upload: static/(.*\.ttf)
  mime_type: application/x-font-ttf

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
